apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.environmentPrefix }}insight-scheduler-deployment
  namespace: {{ .Values.deployment.environmentPrefix }}kta
spec:
  replicas: {{ .Values.role.scheduler.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.environmentPrefix }}insight-scheduler
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.environmentPrefix }}insight-scheduler
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
        - name: {{ .Values.deployment.environmentPrefix }}insight-scheduler
          image: sampleacr.azurecr.io/insightscheduler:v6.4
          resources:
            requests:
              cpu: {{ .Values.role.scheduler.cpu }}
              memory: 1024M
            limits:
              cpu: {{ .Values.role.scheduler.cpulimit }}
              memory: 2048M
          ports:
            - containerPort: {{ .Values.role.scheduler.containerport }}
              name: scheduler
          envFrom:
            - configMapRef:
                name: {{ .Values.deployment.environmentPrefix }}insight-full-config
            - secretRef:
                name: {{ .Values.deployment.environmentPrefix }}insight-secrets-config
          volumeMounts:
            - mountPath: "C:/Temp/InsightData"
              name: {{ .Values.deployment.environmentPrefix }}insight-data-azurefile
      volumes:
        - name: {{ .Values.deployment.environmentPrefix }}insight-data-azurefile
          persistentVolumeClaim:
            claimName: {{ .Values.deployment.environmentPrefix }}insight-data-azurefile
