apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.environmentPrefix }}insight-secrets-config
  namespace: {{ .Values.deployment.environmentPrefix }}kta
type: Opaque
stringData:
  DataService_Insight.Admin.MasterDBConnectionString: "Data Source=<DB_SERVER>; Initial Catalog=InsightAdmin; Password=<DB_PASSWORD>; User Id=<DB_USER>;"
  DataService_Insight.Password: "<REPLACE_ME>"
  DataService_Insight.Admin.MasterDBName: "MS SQL Server"
  Insight_MachineDecryptionKey: "<GENERATE_MACHINE_KEY>"
  Insight_MachineValidationKey: "<GENERATE_MACHINE_KEY>"
  Scheduler_Login: Administrator
  Scheduler_Password: "<REPLACE_ME>"