apiVersion: v1
kind: Secret
metadata:
  name: kta-connection-strings
  namespace: kta
type: Opaque
stringData:
  KTA_MainDB_ConnectionString: "Server=<DB_SERVER>;Trusted_Connection=No;Database=TotalAgility;User Id=<DB_USER>;Password=<DB_PASSWORD>;"
  KTA_FinishDB_ConnectionString: "Server=<DB_SERVER>;Trusted_Connection=No;Database=TotalAgility;User Id=<DB_USER>;Password=<DB_PASSWORD>;"
  KTA_AuditDB_ConnectionString: "Server=<DB_SERVER>;Trusted_Connection=No;Database=TotalAgility;User Id=<DB_USER>;Password=<DB_PASSWORD>;"
  KTA_DocsDB_ConnectionString: "Server=<DB_SERVER>;Trusted_Connection=No;Database=TotalAgility_Documents;User Id=<DB_USER>;Password=<DB_PASSWORD>;"
  KTA_ReportDB_ConnectionString: "Server=<DB_SERVER>;Trusted_Connection=No;Database=TotalAgility_Reporting;User Id=<DB_USER>;Password=<DB_PASSWORD>;"
  KTA_ReportStageDB_ConnectionString: "Server=<DB_SERVER>;Trusted_Connection=No;Database=TotalAgility_Reporting_Staging;User Id=<DB_USER>;Password=<DB_PASSWORD>;"
  KTA_LicenseDB_ConnectionString: "Data Source=<DB_SERVER>;Trusted_Connection=No;Initial Catalog=TotalAgility;User Id=<DB_USER>;Password=<DB_PASSWORD>;"
  

