apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.environmentPrefix }}rpa-mc-service  
  namespace: {{ .Values.deployment.environmentPrefix }}kta  
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Values.deployment.environmentPrefix }}rpa-mc
    