apiVersion: v1
kind: Secret
metadata:
  name: rpa-mc-secrets-config
  namespace: {{ .Values.deployment.environmentPrefix }}kta
type: Opaque
stringData:
  CONTEXT_RESOURCE_VALIDATIONQUERY: "SELECT 1"
  CONTEXT_RESOURCE_USERNAME: "kofaxcoesqladmin"
  CONTEXT_RESOURCE_PASSWORD: "XXXXXXXXX"
  CONTEXT_RESOURCE_DRIVERCLASSNAME: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  CONTEXT_RESOURCE_URL: "jdbc:sqlserver://sample-sql-server.database.windows.net:1433;database=rpa_scheduler;user=kofaxcoesqladmin@kofaxcoesqlserver;password=<DB_PASSWORD>;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
  CONTEXT_CHECK_DATABASE_TIMEOUT: "60"