apiVersion: v1
kind: ConfigMap
metadata:
  name: rpa-rs-config
  namespace: {{ .Values.deployment.environmentPrefix }}kta
data:
  keys:
    ROBOSERVER_ENABLE_MC_REGISTRATION=true
    ROBOSERVER_MC_URL=http://rpa-mc-service:8080/
    ROBOSERVER_MC_CLUSTER=Production
    ROBOSERVER_MC_USERNAME=admin
    ROBOSERVER_MC_PASSWORD=<DB_PASSWORD>
    ROBOSERVER_ENABLE_SOCKET_SERVICE=true
    WRAPPER_MAX_MEMORY=2048
