apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: insight-data-azurefile
  namespace: kta
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
