apiVersion: v1
kind: Secret
metadata:
  name: insight-share-secret
  namespace: kta
type: Opaque
stringData:
  azurestorageaccountname: "ktastore"
  azurestorageaccountkey: "cM2De1PpLcQxZApNTDUlNQFeCQCur5Eg20UsHcZDs6eJBRl5mbgngROQkGi6BpGbO9FJGHx4WPL8IFjPBbd53Q=="