apiVersion: v1
kind: Secret
metadata:
  name: insight-share-secret
  namespace: {{ .Values.deployment.environmentPrefix }}kta
type: Opaque
stringData:
  azurestorageaccountname: "kofaxcoestorage"
  azurestorageaccountkey: "oLeJpOVjmQjiufZowD8kKG6Mu9PNJJ4WzXUloWqfxDz+dl8yFsAUHAkOl5dZ4/ni2IwpmUKi0mnAhyxQ2u7LwA=="