apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.environmentPrefix }}insight-scheduler
  namespace: {{ .Values.deployment.environmentPrefix }}kta 
spec:
  selector:
    app: {{ .Values.deployment.environmentPrefix }}insight-scheduler
  ports:
    - port: 13640