apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.environmentPrefix }}insight-secrets-config
  namespace: {{ .Values.deployment.environmentPrefix }}kta
type: Opaque
stringData:
  DataService_Insight.Admin.MasterDBConnectionString: "Data Source=<DB_SERVER>; Initial Catalog=InsightAdmin2; Password=<DB_PASSWORD>; User Id=<DB_USER>;"
  DataService_Insight.Password: "<REPLACE_ME>"
  DataService_Insight.Admin.MasterDBName: "MS SQL Server"
  Insight_MachineDecryptionKey: "<GENERATE_MACHINE_KEY>"
  Insight_MachineValidationKey: "<GENERATE_MACHINE_KEY>"
  Scheduler_Login: Administrator
  Scheduler_Password: "<REPLACE_ME>"
  DataService_IsDocker: "true"
  DataService_Insight.LicenseFolder: "D:/"
  DataService_UseHighAvailability: "true"
  DataService_Insight.UseIpAddressInsteadOfHost: "true"
  Insight_DataServiceUrl: "https://{{ .Values.deployment.environmentPrefix }}insight-web/WcfDataService/DataService.svc"
  DataService_Insight.Admin.MasterDBProviderName: "sql"
  Insight_HtmlServiceUrl: "https://{{ .Values.deployment.environmentPrefix }}insight-web/WcfDataService/HtmlDataService.svc"
  Insight_ViewerUrl: "https://ktawebappbe/View/Default.aspx"
  ChartSnapshot_Insight.Pdf.AdditionalArguments: "--no-sandbox"
  DataService_Insight.TenantAdmin.MasterDBConnectionString: ""
  SSL_CERT_PASSWORD: "XXXXXXXXX"
  SSL_CERT_PATH: "D:/Certs/ktawebappbe.pfx" 
  WEB_BINDING_HOST_HEADER: "" 
  ROOT_SSL_CERT_PATH: "D:/Certs/ktawebappbe.cer"         
  CA_SSL_CERT_PATH: "D:/Certs/ktawebappbe.cer"
