apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.environmentPrefix }}insight-scheduler-secrets-config
  namespace: {{ .Values.deployment.environmentPrefix }}kta
type: Opaque
stringData:
  Scheduler_Login: Administrator
  Scheduler_Password: "<REPLACE_ME>"
  Scheduler_DataServiceUrl: "https://{{ .Values.deployment.environmentPrefix }}insight-web/WcfDataService/DataService.svc"
  DashboardServer_DataServiceUrl: "https://{{ .Values.deployment.environmentPrefix }}insight-web/WcfDataService/DataService.svc"
  DashboardServer_BridgeServiceURI: "tcp://{{ .Values.deployment.environmentPrefix }}insight-scheduler:15870/IBridgeService.rem"
  Scheduler_UseIpAddressInsteadOfHost: "true"