apiVersion: v1
kind: Secret
metadata:
  name: kta-frontend-tls-secret
  namespace: {{ .Values.deployment.environmentPrefix }}kta
type: kubernetes.io/tls
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlCSlRDQnpRSVVUcDJHQm42b2d3OFd2WjZDK2lSYURpakhFMHN3Q2dZSUtvWkl6ajBFQXdJd0ZqRVVNQklHDQpBMVVFQXd3TGEzUmhkMlZpWVhCd1ltVXdIaGNOTWpJd09ETXhNakF5TXpJMFdoY05Nak13T0RNeE1qQXlNekkwDQpXakFXTVJRd0VnWURWUVFEREF0cmRHRjNaV0poY0hCaVpUQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIDQpBMElBQkNwbjNvRTRhWjROdm1BQ3BWVWdiazVocnFpYW9KN0F2eGt0RGRDOU5aME1nZHJKdnlEYTRoelJNVU5hDQpYKzVYbGpwb0FGZ3FaOWhTTC9iMWlwS2Vjc013Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnUENteTNHMFczZjdrDQpvM01hUnNkK0dwcjliOXRvb1VJOVFWUiszMTNlNlRRQ0lIWGlPMDB6c3JiMTNsRFFZc0ZZY2VTM0pkN05NQ0NyDQpqVkhldHFXUkhzS3kNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCg==
  tls.key: >-
    LS0tLS1CRUdJTiBFQyBQQVJBTUVURVJTLS0tLS0NCkJnZ3Foa2pPUFFNQkJ3PT0NCi0tLS0tRU5EIEVDIFBBUkFNRVRFUlMtLS0tLQ0KLS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tDQpNSGNDQVFFRUlGbnJLblV0TmxTVUJxa2daeXo2L0RVMHh6My94dFZFMmNORmlXVUpxYmRJb0FvR0NDcUdTTTQ5DQpBd0VIb1VRRFFnQUVLbWZlZ1RocG5nMitZQUtsVlNCdVRtR3VxSnFnbnNDL0dTME4wTDAxblF5QjJzbS9JTnJpDQpITkV4UTFwZjdsZVdPbWdBV0NwbjJGSXY5dldLa3A1eXd3PT0NCi0tLS0tRU5EIEVDIFBSSVZBVEUgS0VZLS0tLS0NCg==