apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.deployment.environmentPrefix }}ktamc-ingress
  namespace: {{ .Values.deployment.environmentPrefix }}kta
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/health-probe-path: "/en/file/index.html"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "120"
    appgw.ingress.kubernetes.io/request-timeout: "120"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    # appgw.ingress.kubernetes.io/override-frontend-port: "{{ .Values.role.mc.frontendport }}"
    appgw.ingress.kubernetes.io/backend-hostname: "nonprod.ktamc.kofax.internal.customer.example.com"
    # appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "ExampleCustomer-internal-root-cer"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
    # appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/use-private-ip: "true"
spec:
  tls:
    - secretName: kta-frontend-tls-secret
      hosts:
        - nonprod.ktamc.kofax.internal.customer.example.com
  rules:
    - http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.deployment.environmentPrefix }}kta-mc-service
                port: 
                  number: 80
      host: nonprod.ktamc.kofax.internal.customer.example.com