apiVersion: v1
kind: Secret
metadata:
  name: ktats-secrets-config
  namespace: {{ .Values.deployment.environmentPrefix }}kta
type: Opaque
stringData:
  KTA_TransformationServer--Kofax.CEBPM.CPUServer.ServiceHost.exe.config_MainDBConnectionString: "Server=<DB_SERVER>;Trusted_Connection=No;Database=TotalAgility;User Id=<DB_USER>;Password=<DB_PASSWORD>;"
  KTA_TransformationServer--Kofax.CEBPM.CPUServer.ServiceHost.exe.config_AuditDBConnectionString: "Server=<DB_SERVER>;Trusted_Connection=No;Database=TotalAgility;User Id=<DB_USER>;Password=<DB_PASSWORD>;"
  KTA_TransformationServer--Kofax.CEBPM.CPUServer.ServiceHost.exe.config_ArchiveDBConnectionString: "Server=<DB_SERVER>;Trusted_Connection=No;Database=TotalAgility;User Id=<DB_USER>;Password=<DB_PASSWORD>;"
  KTA_TransformationServer--Kofax.CEBPM.CPUServer.ServiceHost.exe.config_DataLayer: "Server=<DB_SERVER>;Trusted_Connection=No;Database=TotalAgility_Documents;User Id=<DB_USER>;Password=<DB_PASSWORD>;"
  KTA_TransformationServer--Kofax.CEBPM.CPUServer.ServiceHost.exe.config_ReportingMainDBConnectionString: "Server=<DB_SERVER>;Trusted_Connection=No;Database=TotalAgility_Reporting;User Id=<DB_USER>;Password=<DB_PASSWORD>;"
  KTA_TransformationServer--Kofax.CEBPM.CPUServer.ServiceHost.exe.config_ReportingStagingDBConnectionString: "Server=<DB_SERVER>;Trusted_Connection=No;Database=TotalAgility_Reporting_Staging;User Id=<DB_USER>;Password=<DB_PASSWORD>;"
