apiVersion: v1
kind: PersistentVolume
metadata:
  name: kta-azurefile-pvc
  namespace: {{ .Values.deployment.environmentPrefix }}kta
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: kta-share-secret
    shareName: {{ .Values.role.webapp.sharename }}
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=<DB_USER>
  - gid=1000
  - mfsymlinks
  - nobrl