apiVersion: v1
kind: Secret
metadata:
  name: kta-backend-tls-secret
  namespace: {{ .Values.deployment.environmentPrefix }}kta
type: kubernetes.io/tls
data:
  tls.crt: |
        MIIBJTCBzQIUCgOPwRbHzjIRAPeKYBHImNIzOzMwCgYIKoZIzj0EAwIwFjEUMBIG
        A1UEAwwLa3Rhd2ViYXBwYmUwHhcNMjEwODI4MTAwNzU1WhcNMjIwODI4MTAwNzU1
        WjAWMRQwEgYDVQQDDAtrdGF3ZWJhcHBiZTBZMBMGByqGSM49AgEGCCqGSM49AwEH
        A0IABHnMFRG4efpEEgtAHnCpwb+jWUn9NQ0mGCZnXJDJQPf40IWArSpOP7Ainv5B
        uVW16Rdre1rwIMVyCE3jdqkfg4QwCgYIKoZIzj0EAwIDRwAwRAIgIlGwwWhm2jSq
        QUmFG+JO05VcDGrIiovwTcnhVbxt8LwCIDAuQCYCeDpmQM0Bl7530agFKvZ9AgTH
        wDJwhRnYNtvr
  tls.key: |
        MHcCAQEEIIRCUrrxkT4GpNhsx6TqvGvxql1Xg85BT0JDQY6s6XKBoAoGCCqGSM49
        AwEHoUQDQgAEecwVEbh5+kQSC0AecKnBv6NZSf01DSYYJmdckMlA9/jQhYCtKk4/
        sCKe/kG5VbXpF2t7WvAgxXIITeN2qR+DhA==