apiVersion: v1
kind: Secret
metadata:
  name: kta-share-secret
  namespace: {{ .Values.deployment.environmentPrefix }}kta
type: Opaque
stringData:
  azurestorageaccountname: "kofaxcoestorage"
  azurestorageaccountkey: "7l9HOMZewQEHReGlfMLkrCn6kDUko4UtzHDgCrwIsw1IHXUCNiqnmCQeWmSqmP/ieFKibHkkJC3tG0k4pvX7gQ=="