apiVersion: v1
kind: Secret
metadata:
  name: kta-frontend-tls-secret
  namespace: {{ .Values.deployment.environmentPrefix }}kta
type: kubernetes.io/tls
data:
  tls.crt: |
        MIIBJjCBzQIUbXa315yLYgR/j5bocWmYMgK2oYwwCgYIKoZIzj0EAwIwFjEUMBIG
        A1UEAwwLa3Rhd2ViYXBwZmUwHhcNMjEwODI4MTAwMzM0WhcNMjIwODI4MTAwMzM0
        WjAWMRQwEgYDVQQDDAtrdGF3ZWJhcHBmZTBZMBMGByqGSM49AgEGCCqGSM49AwEH
        A0IABPEbvRxKuNW9r265T2mrcKCOoZAJFa1g35hcK9AkLsIF8JRYDhARbkSDgMZe
        b2xfoj2iE1yDeeekpwIIxLaTYxowCgYIKoZIzj0EAwIDSAAwRQIhAK2XZx01omt6
        +dcXmYmpqxvKjQ1vHGOyVFCH+zZ07fN6AiBkIrc4y7KfWpaQEN6bdIsAVsxBZNya
        7rz1CQklVpUAww==
  tls.key: |
        MHcCAQEEIJahHIaGEu+WXood9I/rCvBhpZTTqtuCyHjKEOySnGHzoAoGCCqGSM49
        AwEHoUQDQgAE8Ru9HEq41b2vbrlPaatwoI6hkAkVrWDfmFwr0CQuwgXwlFgOEBFu
        RIOAxl5vbF+iPaITXIN556SnAgjEtpNjGg==