apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.environmentPrefix }}ktareporting-deployment
  namespace: {{ .Values.deployment.environmentPrefix }}kta
spec:
  replicas: {{ .Values.role.reporting.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.environmentPrefix }}kta-reporting
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.environmentPrefix }}kta-reporting
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: ktareporting
        image: sampleacr.azurecr.io/ktareporting:v7.9
        resources:
          requests:
            cpu: {{ .Values.role.reporting.cpu }}
            memory: {{ .Values.role.reporting.memory }}
          limits:
            cpu: {{ .Values.role.reporting.cpulimit }}
            memory: {{ .Values.role.reporting.memorylimit }}
        ports:
          - containerPort: {{ .Values.role.reporting.containerport }}
        envFrom:
          - configMapRef:
              name: kta-full-config
          - secretRef:
              name: kta-secrets-config                