apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.environmentPrefix }}kta-webapp-service  
  namespace: {{ .Values.deployment.environmentPrefix }}kta  
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: {{ .Values.deployment.environmentPrefix }}kta-webapp
    