apiVersion: v1
kind: Secret
metadata:
  name: kta-secrets-config
  namespace: kta
type: Opaque
stringData:
  LicensingDatabase: "Data Source=(local);Integrated Security=True;Initial Catalog=TotalAgility;"
  