# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kvkta-db-config
  namespace: kta  
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: "<GUID>" # Managed identity ID granted KeyVault access previously
    keyvaultName: kvKTA
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: DBConn-TotalAgility-Licensing
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: DBConn-TotalAgility-Live
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: DBConn-TotalAgility-Archive
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: DBConn-TotalAgility-Audit
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: DBConn-TotalAgility-Documents
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: DBConn-TotalAgility-ReportingStaging
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: DBConn-TotalAgility-Reporting
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    tenantId: <GUID>           # The tenant ID of the key vault
  secretObjects:
    - secretName: kta-secrets-db-config
      type: Opaque
      data:
      - key: LicensingDatabase
        objectName: DBConn-TotalAgility-Licensing
      - key: KTA_CoreWorkerService--Agility.Server.Core.WorkerService.exe.config_MainDBConnectionString
        objectName: DBConn-TotalAgility-Live
      - key: KTA_CoreWorkerService--Agility.Server.StreamingService.exe.config_MainDBConnectionString
        objectName: DBConn-TotalAgility-Live
      - key: KTA_Agility.Server.Web--bin--Agility.Server.StreamingService.exe.config_MainDBConnectionString
        objectName: DBConn-TotalAgility-Live
      - key: KTA_Agility.Server.Web--web.config_MainDBConnectionString
        objectName: DBConn-TotalAgility-Live
      - key: KTA_Agility.Server.Web--bin--Agility.Server.Core.Executor.exe.config_MainDBConnectionString
        objectName: DBConn-TotalAgility-Live
      - key: KTA_Agility.Server.Web.TenantManagement--web.config_MainDBConnectionString
        objectName: DBConn-TotalAgility-Live
      - key: KTA_CoreWorkerService--Agility.Server.Core.WorkerService.exe.config_ArchiveDBConnectionString
        objectName: DBConn-TotalAgility-Archive
      - key: KTA_CoreWorkerService--Agility.Server.StreamingService.exe.config_ArchiveDBConnectionString
        objectName: DBConn-TotalAgility-Archive
      - key: KTA_Agility.Server.Web--bin--Agility.Server.StreamingService.exe.config_ArchiveDBConnectionString
        objectName: DBConn-TotalAgility-Archive
      - key: KTA_Agility.Server.Web--web.config_ArchiveDBConnectionString
        objectName: DBConn-TotalAgility-Archive
      - key: KTA_Agility.Server.Web.TenantManagement--web.config_ArchiveDBConnectionString
        objectName: DBConn-TotalAgility-Archive
      - key: KTA_Agility.Server.Web--bin--Agility.Server.Core.Executor.exe.config_ArchiveDBConnectionString
        objectName: DBConn-TotalAgility-Archive
      - key: KTA_CoreWorkerService--Agility.Server.Core.Executor.exe.config_ArchiveDBConnectionString
        objectName: DBConn-TotalAgility-Archive  
      - key: KTA_CoreWorkerService--Agility.Server.Core.WorkerService.exe.config_DataLayer
        objectName: DBConn-TotalAgility-Documents
      - key: KTA_CoreWorkerService--Agility.Server.StreamingService.exe.config_DataLayer
        objectName: DBConn-TotalAgility-Documents
      - key: KTA_Agility.Server.Web--bin--Agility.Server.StreamingService.exe.config_DataLayer
        objectName: DBConn-TotalAgility-Documents
      - key: KTA_Agility.Server.Web--web.config_DataLayer
        objectName: DBConn-TotalAgility-Documents
      - key: KTA_Agility.Server.Web.TenantManagement--web.config_DataLayer
        objectName: DBConn-TotalAgility-Documents
      - key: KTA_Agility.Server.Web--bin--Agility.Server.Core.Executor.exe.config_DataLayer
        objectName: DBConn-TotalAgility-Documents
      - key: KTA_CoreWorkerService--Agility.Server.Core.Executor.exe.config_DataLayer
        objectName: DBConn-TotalAgility-Documents
      - key: KTA_CoreWorkerService--Agility.Server.Core.WorkerService.exe.config_AuditDBConnectionString
        objectName: DBConn-TotalAgility-Audit
      - key: KTA_CoreWorkerService--Agility.Server.StreamingService.exe.config_AuditDBConnectionString
        objectName: DBConn-TotalAgility-Audit
      - key: KTA_Agility.Server.Web--bin--Agility.Server.StreamingService.exe.config_AuditDBConnectionString
        objectName: DBConn-TotalAgility-Audit
      - key: KTA_Agility.Server.Web--web.config_AuditDBConnectionString
        objectName: DBConn-TotalAgility-Audit
      - key: KTA_Agility.Server.Web--bin--Agility.Server.Core.Executor.exe.config_AuditDBConnectionString
        objectName: DBConn-TotalAgility-Audit
      - key: KTA_CoreWorkerService--Agility.Server.Core.Executor.exe.config_AuditDBConnectionString
        objectName: DBConn-TotalAgility-Audit
      - key: KTA_CoreWorkerService--Agility.Server.Core.WorkerService.exe.config_ReportingStagingDBConnectionString
        objectName: DBConn-TotalAgility-ReportingStaging
      - key: KTA_CoreWorkerService--Agility.Server.StreamingService.exe.config_ReportingStagingDBConnectionString
        objectName: DBConn-TotalAgility-ReportingStaging
      - key: KTA_Agility.Server.Web--bin--Agility.Server.StreamingService.exe.config_ReportingStagingDBConnectionString
        objectName: DBConn-TotalAgility-ReportingStaging
      - key: KTA_Agility.Server.Web--web.config_ReportingStagingDBConnectionString
        objectName: DBConn-TotalAgility-ReportingStaging
      - key: KTA_Agility.Server.Web.TenantManagement--web.config_ReportingStagingDBConnectionString
        objectName: DBConn-TotalAgility-ReportingStaging
      - key: KTA_Agility.Server.Web--bin--Agility.Server.Core.Executor.exe.config_ReportingStagingDBConnectionString
        objectName: DBConn-TotalAgility-ReportingStaging
      - key: KTA_CoreWorkerService--Agility.Server.Core.Executor.exe.config_ReportingStagingDBConnectionString
        objectName: DBConn-TotalAgility-ReportingStaging
      - key: KTA_CoreWorkerService--Agility.Server.Core.WorkerService.exe.config_ReportingMainDBConnectionString
        objectName: DBConn-TotalAgility-ReportingStaging
      - key: KTA_CoreWorkerService--Agility.Server.StreamingService.exe.config_ReportingMainDBConnectionString
        objectName: DBConn-TotalAgility-ReportingStaging
      - key: KTA_Agility.Server.Web--bin--Agility.Server.StreamingService.exe.config_ReportingMainDBConnectionString
        objectName: DBConn-TotalAgility-ReportingStaging
      - key: KTA_Agility.Server.Web--web.config_ReportingMainDBConnectionString
        objectName: DBConn-TotalAgility-ReportingStaging
      - key: KTA_Agility.Server.Web.TenantManagement--web.config_ReportingMainDBConnectionString
        objectName: DBConn-TotalAgility-ReportingStaging
      - key: KTA_Agility.Server.Web--bin--Agility.Server.Core.Executor.exe.config_ReportingMainDBConnectionString
        objectName: DBConn-TotalAgility-ReportingStaging
      - key: KTA_CoreWorkerService--Agility.Server.Core.Executor.exe.config_ReportingMainDBConnectionString
        objectName: DBConn-TotalAgility-ReportingStaging
        